/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsNewRouteImport } from './routes/projects/new'
import { Route as JoinTokenRouteImport } from './routes/join/$token'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as ProjectsProjectIdStandupRouteImport } from './routes/projects/$projectId/standup'
import { Route as ProjectsProjectIdMembersRouteImport } from './routes/projects/$projectId/members'
import { Route as ProjectsProjectIdInviteLinksRouteImport } from './routes/projects/$projectId/invite-links'
import { Route as ProjectsProjectIdBriefRouteImport } from './routes/projects/$projectId/brief'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/projects/new',
  path: '/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/projects/$projectId/',
  path: '/projects/$projectId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdStandupRoute =
  ProjectsProjectIdStandupRouteImport.update({
    id: '/projects/$projectId/standup',
    path: '/projects/$projectId/standup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdMembersRoute =
  ProjectsProjectIdMembersRouteImport.update({
    id: '/projects/$projectId/members',
    path: '/projects/$projectId/members',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdInviteLinksRoute =
  ProjectsProjectIdInviteLinksRouteImport.update({
    id: '/projects/$projectId/invite-links',
    path: '/projects/$projectId/invite-links',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdBriefRoute = ProjectsProjectIdBriefRouteImport.update({
  id: '/projects/$projectId/brief',
  path: '/projects/$projectId/brief',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join/$token': typeof JoinTokenRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/brief': typeof ProjectsProjectIdBriefRoute
  '/projects/$projectId/invite-links': typeof ProjectsProjectIdInviteLinksRoute
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/standup': typeof ProjectsProjectIdStandupRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join/$token': typeof JoinTokenRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/brief': typeof ProjectsProjectIdBriefRoute
  '/projects/$projectId/invite-links': typeof ProjectsProjectIdInviteLinksRoute
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/standup': typeof ProjectsProjectIdStandupRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/join/$token': typeof JoinTokenRoute
  '/projects/new': typeof ProjectsNewRoute
  '/projects/$projectId/brief': typeof ProjectsProjectIdBriefRoute
  '/projects/$projectId/invite-links': typeof ProjectsProjectIdInviteLinksRoute
  '/projects/$projectId/members': typeof ProjectsProjectIdMembersRoute
  '/projects/$projectId/standup': typeof ProjectsProjectIdStandupRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/join/$token'
    | '/projects/new'
    | '/projects/$projectId/brief'
    | '/projects/$projectId/invite-links'
    | '/projects/$projectId/members'
    | '/projects/$projectId/standup'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/join/$token'
    | '/projects/new'
    | '/projects/$projectId/brief'
    | '/projects/$projectId/invite-links'
    | '/projects/$projectId/members'
    | '/projects/$projectId/standup'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/join/$token'
    | '/projects/new'
    | '/projects/$projectId/brief'
    | '/projects/$projectId/invite-links'
    | '/projects/$projectId/members'
    | '/projects/$projectId/standup'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  JoinTokenRoute: typeof JoinTokenRoute
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsProjectIdBriefRoute: typeof ProjectsProjectIdBriefRoute
  ProjectsProjectIdInviteLinksRoute: typeof ProjectsProjectIdInviteLinksRoute
  ProjectsProjectIdMembersRoute: typeof ProjectsProjectIdMembersRoute
  ProjectsProjectIdStandupRoute: typeof ProjectsProjectIdStandupRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/standup': {
      id: '/projects/$projectId/standup'
      path: '/projects/$projectId/standup'
      fullPath: '/projects/$projectId/standup'
      preLoaderRoute: typeof ProjectsProjectIdStandupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/members': {
      id: '/projects/$projectId/members'
      path: '/projects/$projectId/members'
      fullPath: '/projects/$projectId/members'
      preLoaderRoute: typeof ProjectsProjectIdMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/invite-links': {
      id: '/projects/$projectId/invite-links'
      path: '/projects/$projectId/invite-links'
      fullPath: '/projects/$projectId/invite-links'
      preLoaderRoute: typeof ProjectsProjectIdInviteLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/brief': {
      id: '/projects/$projectId/brief'
      path: '/projects/$projectId/brief'
      fullPath: '/projects/$projectId/brief'
      preLoaderRoute: typeof ProjectsProjectIdBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  JoinTokenRoute: JoinTokenRoute,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsProjectIdBriefRoute: ProjectsProjectIdBriefRoute,
  ProjectsProjectIdInviteLinksRoute: ProjectsProjectIdInviteLinksRoute,
  ProjectsProjectIdMembersRoute: ProjectsProjectIdMembersRoute,
  ProjectsProjectIdStandupRoute: ProjectsProjectIdStandupRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
